- name: Install yum utils
  yum:
    name: yum-utils
    state: latest

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Install Docker (yum)
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - curl
    - docker-ce
    - docker-ce-cli
    - containerd.io
